pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }
    environment {
        cluser = 'vproprod'
        service = 'vproappprodsvc'
    }
    stages {
        stage ('Deploy to Staging')  {
            steps{
                withAWS(credentials: 'awscredentional', region: 'us-west-1' ) {
                    sh 'aws esc update-service --cluster ${cluster} --service ${service} --force-new-deployment' 
                }
            }
        }
    }
}