pipeline {
    agent any
    tools {
        maven "MAVEN3"
        jdk "OracleJDK8"
    }
    environment {
        cluster = 'vproprod'
        service = 'vproappprodsvc'
    }
    stages {
        stage ('Deploy to Staging')  {
            steps{
                withAWS(credentials: 'awscredentional', region: 'us-east-1' ) {
                    sh 'aws ecs update-service --cluster ${cluster} --service ${service} --force-new-deployment' 
                }
            }
        }
    }
}