name: Hprofile Actions
on: workflow_dispatch
jobs:
  Testing:
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Maven test
        run: mvn test

      - name: Checkstyle
        run: mvn checkstyle:chechstyle
